language: rust
rust:
  - stable
cache: cargo

os:
  linux

addons:
  apt:
    packages:
      - libasound2-dev
      - libxcb-shape0-dev
      - libxcb-xfixes0-dev

before_script:
  - rustup component add clippy
  - rustup component add rustfmt

script:
  - cargo fmt -- --check
  - cargo clippy -- -D warnings
  - cargo build --verbose
  - cargo test --verbose